spring:
    datasource:
        url: jdbc:h2:mem:desafioclaro
        username: claro123
        password:
    jpa:
        show-sql: true
        open-in-virew: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
